swagger: "2.0"
info:
  description: "This is a simple server to support 5gzorro data lake operations."
  version: "1.0.0"
  title: "Data Lake API"
  contact:
    email: "meth@il.ibm.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
#host: "datalake.5gzorro.eu"
basePath: "/datalake/v1"
tags:
- name: "user"
  description: "Register/unregister users"
- name: "pipeline"
  description: "Operations on pipelines"
schemes:
- "https"
- "http"
paths:
  /user:
    post:
      tags:
      - "user"
      summary: "Register a new user"
      description: ""
      operationId: "registerUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Parameters to register User that is connecting to the services of the Data Lake"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "201":
          description: "successful operation"
          schema:
            $ref: "#/definitions/UserResources"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
    delete:
      tags:
      - "user"
      summary: "Unregister a user"
      description: ""
      operationId: "unregisterUser"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Parameters to unregister User from the Data Lake"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "204":
          description: "User unregistered successfully"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "404":
          description: "User not found"
  /user/all:
    get:
      tags:
      - "user"
      summary: "List all User IDs"
      description: ""
      operationId: "listUsers"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "string"
        "400":
          description: "Bad Request"
  /pipeline:
    post:
      tags:
      - "pipeline"
      summary: "Register a new pipeline"
      description: ""
      operationId: "createPipeline"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Parameters to register pipeline"
        required: true
        schema:
          $ref: "#/definitions/CreatePipeline"
      responses:
        "201":
          description: "successful operation"
          schema:
            $ref: "#/definitions/PipelineMetadata"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
    delete:
      tags:
      - "pipeline"
      summary: "Delete a pipeline"
      description: ""
      operationId: "deletePipeline"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Parameters to delete a pipeline"
        required: true
        schema:
          $ref: "#/definitions/GetPipeline"
      responses:
        "204":
          description: "Pipeline deleted successfully"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "404":
          description: "Pipeline not found"
    get:
      tags:
      - "pipeline"
      summary: "Return details of specified pipeline"
      description: ""
      operationId: "getPipeline"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Parameters to get a pipeline"
        required: true
        schema:
          $ref: "#/definitions/GetPipeline"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/PipelineInfo"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "404":
          description: "Pipeline not found"
  /pipeline/all:
    get:
      tags:
      - "pipeline"
      summary: "List all of the User's pipelines"
      description: ""
      operationId: "listPipelines"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PipelineInfo"
        "400":
          description: "Bad Request"
definitions:
  User:
    type: "object"
    properties:
      userId:
        type: "string"
      authToken:
        type: "string"
    xml:
      name: "User"
  UserResources:
    type: "object"
    properties:
      nameSpace:
        type: "string"
      availableResources:
        type: "object"
    xml:
      name: "UserResources"
  CreatePipeline:
    type: "object"
    properties:
      userInfo:
        $ref: "#/definitions/User"
      pipelineDefinition:
        type: "object"
    xml:
      name: "CreatePipeline"
  GetPipeline:
    type: "object"
    properties:
      userInfo:
        $ref: "#/definitions/User"
      pipelineId:
        type: "string"
    xml:
      name: "GetPipeline"
  PipelineMetadata:
    type: "object"
    properties:
      pipelineId:
        type: "string"
      inputTopic:
        type: "string"
      outputTopic:
        type: "string"
    xml:
      name: "PipelineMetadata"
  PipelineInfo:  
    type: "object"
    properties:
      pipelineMetadata:
        $ref: "#/definitions/PipelineMetadata"
      pipelineDefinition:
        type: "object"
    xml:
      name: "PipelineInfo"
 
