# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util
from swagger_server.models.user import User


class CreatePipeline(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_info: User=None, pipeline_definition: object=None):  # noqa: E501
        """CreatePipeline - a model defined in Swagger

        :param user_info: The user_info of this CreatePipeline.  # noqa: E501
        :type user_info: User
        :param pipeline_definition: The pipeline_definition of this CreatePipeline.  # noqa: E501
        :type pipeline_definition: object
        """
        self.swagger_types = {
            'user_info': User,
            'pipeline_definition': object
        }

        self.attribute_map = {
            'user_info': 'userInfo',
            'pipeline_definition': 'pipelineDefinition'
        }

        self._user_info = user_info
        self._pipeline_definition = pipeline_definition

    @classmethod
    def from_dict(cls, dikt) -> 'CreatePipeline':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreatePipeline of this CreatePipeline.  # noqa: E501
        :rtype: CreatePipeline
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_info(self) -> User:
        """Gets the user_info of this CreatePipeline.


        :return: The user_info of this CreatePipeline.
        :rtype: User
        """
        return self._user_info

    @user_info.setter
    def user_info(self, user_info: User):
        """Sets the user_info of this CreatePipeline.


        :param user_info: The user_info of this CreatePipeline.
        :type user_info: User
        """

        self._user_info = user_info

    @property
    def pipeline_definition(self) -> object:
        """Gets the pipeline_definition of this CreatePipeline.


        :return: The pipeline_definition of this CreatePipeline.
        :rtype: object
        """
        return self._pipeline_definition

    @pipeline_definition.setter
    def pipeline_definition(self, pipeline_definition: object):
        """Sets the pipeline_definition of this CreatePipeline.


        :param pipeline_definition: The pipeline_definition of this CreatePipeline.
        :type pipeline_definition: object
        """

        self._pipeline_definition = pipeline_definition
