# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util
from swagger_server.models.user import User


class GetPipeline(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_info: User=None, pipeline_id: str=None):  # noqa: E501
        """GetPipeline - a model defined in Swagger

        :param user_info: The user_info of this GetPipeline.  # noqa: E501
        :type user_info: User
        :param pipeline_id: The pipeline_id of this GetPipeline.  # noqa: E501
        :type pipeline_id: str
        """
        self.swagger_types = {
            'user_info': User,
            'pipeline_id': str
        }

        self.attribute_map = {
            'user_info': 'userInfo',
            'pipeline_id': 'pipelineId'
        }

        self._user_info = user_info
        self._pipeline_id = pipeline_id

    @classmethod
    def from_dict(cls, dikt) -> 'GetPipeline':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetPipeline of this GetPipeline.  # noqa: E501
        :rtype: GetPipeline
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_info(self) -> User:
        """Gets the user_info of this GetPipeline.


        :return: The user_info of this GetPipeline.
        :rtype: User
        """
        return self._user_info

    @user_info.setter
    def user_info(self, user_info: User):
        """Sets the user_info of this GetPipeline.


        :param user_info: The user_info of this GetPipeline.
        :type user_info: User
        """

        self._user_info = user_info

    @property
    def pipeline_id(self) -> str:
        """Gets the pipeline_id of this GetPipeline.


        :return: The pipeline_id of this GetPipeline.
        :rtype: str
        """
        return self._pipeline_id

    @pipeline_id.setter
    def pipeline_id(self, pipeline_id: str):
        """Sets the pipeline_id of this GetPipeline.


        :param pipeline_id: The pipeline_id of this GetPipeline.
        :type pipeline_id: str
        """

        self._pipeline_id = pipeline_id
