# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util
from swagger_server.models.user import User


class GetService(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_info: User=None, service_id: str=None):  # noqa: E501
        """GetService - a model defined in Swagger

        :param user_info: The user_info of this GetService.  # noqa: E501
        :type user_info: User
        :param service_id: The service_id of this GetService.  # noqa: E501
        :type service_id: str
        """
        self.swagger_types = {
            'user_info': User,
            'service_id': str
        }

        self.attribute_map = {
            'user_info': 'userInfo',
            'service_id': 'serviceId'
        }

        self._user_info = user_info
        self._service_id = service_id

    @classmethod
    def from_dict(cls, dikt) -> 'GetService':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetService of this GetService.  # noqa: E501
        :rtype: GetService
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_info(self) -> User:
        """Gets the user_info of this GetService.


        :return: The user_info of this GetService.
        :rtype: User
        """
        return self._user_info

    @user_info.setter
    def user_info(self, user_info: User):
        """Sets the user_info of this GetService.


        :param user_info: The user_info of this GetService.
        :type user_info: User
        """

        self._user_info = user_info

    @property
    def service_id(self) -> str:
        """Gets the service_id of this GetService.


        :return: The service_id of this GetService.
        :rtype: str
        """
        return self._service_id

    @service_id.setter
    def service_id(self, service_id: str):
        """Sets the service_id of this GetService.


        :param service_id: The service_id of this GetService.
        :type service_id: str
        """

        self._service_id = service_id
