# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util
from swagger_server.models.pipeline_metadata import PipelineMetadata


class PipelineInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, pipeline_metadata: PipelineMetadata=None, pipeline_definition: object=None):  # noqa: E501
        """PipelineInfo - a model defined in Swagger

        :param pipeline_metadata: The pipeline_metadata of this PipelineInfo.  # noqa: E501
        :type pipeline_metadata: PipelineMetadata
        :param pipeline_definition: The pipeline_definition of this PipelineInfo.  # noqa: E501
        :type pipeline_definition: object
        """
        self.swagger_types = {
            'pipeline_metadata': PipelineMetadata,
            'pipeline_definition': object
        }

        self.attribute_map = {
            'pipeline_metadata': 'pipelineMetadata',
            'pipeline_definition': 'pipelineDefinition'
        }

        self._pipeline_metadata = pipeline_metadata
        self._pipeline_definition = pipeline_definition

    @classmethod
    def from_dict(cls, dikt) -> 'PipelineInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PipelineInfo of this PipelineInfo.  # noqa: E501
        :rtype: PipelineInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pipeline_metadata(self) -> PipelineMetadata:
        """Gets the pipeline_metadata of this PipelineInfo.


        :return: The pipeline_metadata of this PipelineInfo.
        :rtype: PipelineMetadata
        """
        return self._pipeline_metadata

    @pipeline_metadata.setter
    def pipeline_metadata(self, pipeline_metadata: PipelineMetadata):
        """Sets the pipeline_metadata of this PipelineInfo.


        :param pipeline_metadata: The pipeline_metadata of this PipelineInfo.
        :type pipeline_metadata: PipelineMetadata
        """

        self._pipeline_metadata = pipeline_metadata

    @property
    def pipeline_definition(self) -> object:
        """Gets the pipeline_definition of this PipelineInfo.


        :return: The pipeline_definition of this PipelineInfo.
        :rtype: object
        """
        return self._pipeline_definition

    @pipeline_definition.setter
    def pipeline_definition(self, pipeline_definition: object):
        """Sets the pipeline_definition of this PipelineInfo.


        :param pipeline_definition: The pipeline_definition of this PipelineInfo.
        :type pipeline_definition: object
        """

        self._pipeline_definition = pipeline_definition
