# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PipelineDeleteInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_id: str=None, auth_token: str=None, pipeline_id: str=None):  # noqa: E501
        """PipelineDeleteInfo - a model defined in Swagger

        :param user_id: The user_id of this PipelineDeleteInfo.  # noqa: E501
        :type user_id: str
        :param auth_token: The auth_token of this PipelineDeleteInfo.  # noqa: E501
        :type auth_token: str
        :param pipeline_id: The pipeline_id of this PipelineDeleteInfo.  # noqa: E501
        :type pipeline_id: str
        """
        self.swagger_types = {
            'user_id': str,
            'auth_token': str,
            'pipeline_id': str
        }

        self.attribute_map = {
            'user_id': 'userId',
            'auth_token': 'authToken',
            'pipeline_id': 'pipelineId'
        }

        self._user_id = user_id
        self._auth_token = auth_token
        self._pipeline_id = pipeline_id

    @classmethod
    def from_dict(cls, dikt) -> 'PipelineDeleteInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PipelineDeleteInfo of this PipelineDeleteInfo.  # noqa: E501
        :rtype: PipelineDeleteInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this PipelineDeleteInfo.


        :return: The user_id of this PipelineDeleteInfo.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this PipelineDeleteInfo.


        :param user_id: The user_id of this PipelineDeleteInfo.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def auth_token(self) -> str:
        """Gets the auth_token of this PipelineDeleteInfo.


        :return: The auth_token of this PipelineDeleteInfo.
        :rtype: str
        """
        return self._auth_token

    @auth_token.setter
    def auth_token(self, auth_token: str):
        """Sets the auth_token of this PipelineDeleteInfo.


        :param auth_token: The auth_token of this PipelineDeleteInfo.
        :type auth_token: str
        """

        self._auth_token = auth_token

    @property
    def pipeline_id(self) -> str:
        """Gets the pipeline_id of this PipelineDeleteInfo.


        :return: The pipeline_id of this PipelineDeleteInfo.
        :rtype: str
        """
        return self._pipeline_id

    @pipeline_id.setter
    def pipeline_id(self, pipeline_id: str):
        """Sets the pipeline_id of this PipelineDeleteInfo.


        :param pipeline_id: The pipeline_id of this PipelineDeleteInfo.
        :type pipeline_id: str
        """

        self._pipeline_id = pipeline_id
