# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ServiceMetadata(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, service_id: str=None, input_topic: str=None, output_topic: str=None, ports: List[object]=None):  # noqa: E501
        """ServiceMetadata - a model defined in Swagger

        :param service_id: The service_id of this ServiceMetadata.  # noqa: E501
        :type service_id: str
        :param input_topic: The input_topic of this ServiceMetadata.  # noqa: E501
        :type input_topic: str
        :param output_topic: The output_topic of this ServiceMetadata.  # noqa: E501
        :type output_topic: str
        :param ports: The ports of this ServiceMetadata.  # noqa: E501
        :type ports: List[object]
        """
        self.swagger_types = {
            'service_id': str,
            'input_topic': str,
            'output_topic': str,
            'ports': List[object]
        }

        self.attribute_map = {
            'service_id': 'serviceId',
            'input_topic': 'inputTopic',
            'output_topic': 'outputTopic',
            'ports': 'ports'
        }

        self._service_id = service_id
        self._input_topic = input_topic
        self._output_topic = output_topic
        self._ports = ports

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceMetadata of this ServiceMetadata.  # noqa: E501
        :rtype: ServiceMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_id(self) -> str:
        """Gets the service_id of this ServiceMetadata.


        :return: The service_id of this ServiceMetadata.
        :rtype: str
        """
        return self._service_id

    @service_id.setter
    def service_id(self, service_id: str):
        """Sets the service_id of this ServiceMetadata.


        :param service_id: The service_id of this ServiceMetadata.
        :type service_id: str
        """

        self._service_id = service_id

    @property
    def input_topic(self) -> str:
        """Gets the input_topic of this ServiceMetadata.


        :return: The input_topic of this ServiceMetadata.
        :rtype: str
        """
        return self._input_topic

    @input_topic.setter
    def input_topic(self, input_topic: str):
        """Sets the input_topic of this ServiceMetadata.


        :param input_topic: The input_topic of this ServiceMetadata.
        :type input_topic: str
        """

        self._input_topic = input_topic

    @property
    def output_topic(self) -> str:
        """Gets the output_topic of this ServiceMetadata.


        :return: The output_topic of this ServiceMetadata.
        :rtype: str
        """
        return self._output_topic

    @output_topic.setter
    def output_topic(self, output_topic: str):
        """Sets the output_topic of this ServiceMetadata.


        :param output_topic: The output_topic of this ServiceMetadata.
        :type output_topic: str
        """

        self._output_topic = output_topic

    @property
    def ports(self) -> List[object]:
        """Gets the ports of this ServiceMetadata.


        :return: The ports of this ServiceMetadata.
        :rtype: List[object]
        """
        return self._ports

    @ports.setter
    def ports(self, ports: List[object]):
        """Sets the ports of this ServiceMetadata.


        :param ports: The ports of this ServiceMetadata.
        :type ports: List[object]
        """

        self._ports = ports
