apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ingest-
spec:
  entrypoint: handlerequest
  imagePullSecrets:
  - name: myregistrykey
  arguments:
    parameters:
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Payload parameters to be
    # overriden by the event values
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: operatorID
      value: OVERRIDE

    - name: businessID
      value: OVERRIDE

    - name: networkID
      value: OVERRIDE

    - name: monitoringData
      value: OVERRIDE

  templates:
  - name: handlerequest
    dag:
      tasks:
      - name: print-message
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "Received metric. operatorID: {{workflow.parameters.operatorID}}, businessID: {{workflow.parameters.businessID}}, networkID: {{workflow.parameters.networkID}}, monitoringData: {{workflow.parameters.monitoringData}}"

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
