# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User
from swagger_server.models.time_interval import TimeInterval
from swagger_server import util


class ResourceQuery(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_info: User=None, time_info: TimeInterval=None):  # noqa: E501
        """ResourceQuery - a model defined in Swagger

        :param user_info: The user_info of this ResourceQuery.  # noqa: E501
        :type user_info: User
        :param time_info: The time_info of this ResourceQuery.  # noqa: E501
        :type time_info: TimeInterval
        """
        self.swagger_types = {
            'user_info': User,
            'time_info': TimeInterval
        }

        self.attribute_map = {
            'user_info': 'userInfo',
            'time_info': 'timeInfo'
        }

        self._user_info = user_info
        self._time_info = time_info

    @classmethod
    def from_dict(cls, dikt) -> 'ResourceQuery':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResourceQuery of this ResourceQuery.  # noqa: E501
        :rtype: ResourceQuery
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_info(self) -> User:
        """Gets the user_info of this ResourceQuery.


        :return: The user_info of this ResourceQuery.
        :rtype: User
        """
        return self._user_info

    @user_info.setter
    def user_info(self, user_info: User):
        """Sets the user_info of this ResourceQuery.


        :param user_info: The user_info of this ResourceQuery.
        :type user_info: User
        """

        self._user_info = user_info

    @property
    def time_info(self) -> TimeInterval:
        """Gets the time_info of this ResourceQuery.


        :return: The time_info of this ResourceQuery.
        :rtype: TimeInterval
        """
        return self._time_info

    @time_info.setter
    def time_info(self, time_info: TimeInterval):
        """Sets the time_info of this ResourceQuery.


        :param time_info: The time_info of this ResourceQuery.
        :type time_info: TimeInterval
        """

        self._time_info = time_info
