# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResourceEntriesInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, resource_id: str=None, reference_id: str=None, metric_name: str=None, metric_value: str=None, timestamp: str=None, storage_location: str=None):  # noqa: E501
        """ResourceEntriesInfo - a model defined in Swagger

        :param resource_id: The resource_id of this ResourceEntriesInfo.  # noqa: E501
        :type resource_id: str
        :param reference_id: The reference_id of this ResourceEntriesInfo.  # noqa: E501
        :type reference_id: str
        :param metric_name: The metric_name of this ResourceEntriesInfo.  # noqa: E501
        :type metric_name: str
        :param metric_value: The metric_value of this ResourceEntriesInfo.  # noqa: E501
        :type metric_value: str
        :param timestamp: The timestamp of this ResourceEntriesInfo.  # noqa: E501
        :type timestamp: str
        :param storage_location: The storage_location of this ResourceEntriesInfo.  # noqa: E501
        :type storage_location: str
        """
        self.swagger_types = {
            'resource_id': str,
            'reference_id': str,
            'metric_name': str,
            'metric_value': str,
            'timestamp': str,
            'storage_location': str
        }

        self.attribute_map = {
            'resource_id': 'resourceId',
            'reference_id': 'referenceId',
            'metric_name': 'metricName',
            'metric_value': 'metricValue',
            'timestamp': 'timestamp',
            'storage_location': 'storageLocation'
        }

        self._resource_id = resource_id
        self._reference_id = reference_id
        self._metric_name = metric_name
        self._metric_value = metric_value
        self._timestamp = timestamp
        self._storage_location = storage_location

    @classmethod
    def from_dict(cls, dikt) -> 'ResourceEntriesInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResourceEntriesInfo of this ResourceEntriesInfo.  # noqa: E501
        :rtype: ResourceEntriesInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def resource_id(self) -> str:
        """Gets the resource_id of this ResourceEntriesInfo.


        :return: The resource_id of this ResourceEntriesInfo.
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id: str):
        """Sets the resource_id of this ResourceEntriesInfo.


        :param resource_id: The resource_id of this ResourceEntriesInfo.
        :type resource_id: str
        """

        self._resource_id = resource_id

    @property
    def reference_id(self) -> str:
        """Gets the reference_id of this ResourceEntriesInfo.


        :return: The reference_id of this ResourceEntriesInfo.
        :rtype: str
        """
        return self._reference_id

    @reference_id.setter
    def reference_id(self, reference_id: str):
        """Sets the reference_id of this ResourceEntriesInfo.


        :param reference_id: The reference_id of this ResourceEntriesInfo.
        :type reference_id: str
        """

        self._reference_id = reference_id

    @property
    def metric_name(self) -> str:
        """Gets the metric_name of this ResourceEntriesInfo.


        :return: The metric_name of this ResourceEntriesInfo.
        :rtype: str
        """
        return self._metric_name

    @metric_name.setter
    def metric_name(self, metric_name: str):
        """Sets the metric_name of this ResourceEntriesInfo.


        :param metric_name: The metric_name of this ResourceEntriesInfo.
        :type metric_name: str
        """

        self._metric_name = metric_name

    @property
    def metric_value(self) -> str:
        """Gets the metric_value of this ResourceEntriesInfo.


        :return: The metric_value of this ResourceEntriesInfo.
        :rtype: str
        """
        return self._metric_value

    @metric_value.setter
    def metric_value(self, metric_value: str):
        """Sets the metric_value of this ResourceEntriesInfo.


        :param metric_value: The metric_value of this ResourceEntriesInfo.
        :type metric_value: str
        """

        self._metric_value = metric_value

    @property
    def timestamp(self) -> str:
        """Gets the timestamp of this ResourceEntriesInfo.


        :return: The timestamp of this ResourceEntriesInfo.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: str):
        """Sets the timestamp of this ResourceEntriesInfo.


        :param timestamp: The timestamp of this ResourceEntriesInfo.
        :type timestamp: str
        """

        self._timestamp = timestamp

    @property
    def storage_location(self) -> str:
        """Gets the storage_location of this ResourceEntriesInfo.


        :return: The storage_location of this ResourceEntriesInfo.
        :rtype: str
        """
        return self._storage_location

    @storage_location.setter
    def storage_location(self, storage_location: str):
        """Sets the storage_location of this ResourceEntriesInfo.


        :param storage_location: The storage_location of this ResourceEntriesInfo.
        :type storage_location: str
        """

        self._storage_location = storage_location
