---
swagger: "2.0"
info:
  description: "This is a simple server to support 5gzorro data lake stream data operations."
  version: "1.0.0"
  title: "Data Lake Stream Data Service API"
  contact:
    email: "meth@il.ibm.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/datalake/v1/stream_data"
tags:
- name: "product"
  description: "Operations on product ID"
schemes:
- "https"
- "http"
paths:
  /register/{productId}:
    post:
      tags:
      - "product"
      summary: "register productId for which data should be streamed"
      description: ""
      operationId: "register_product_topic"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Parameters to get a entries related to productId"
        required: true
        schema:
          $ref: "#/definitions/ProductQuery"
      responses:
        "201":
          description: "successful operation"
      x-swagger-router-controller: "swagger_server.controllers.product_controller"
  /unregister/{productId}:
    post:
      tags:
      - "product"
      summary: "stop stream data for specified  productId"
      description: ""
      operationId: "unregister_product_topic"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Parameters to unregister streaming for productId"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "204":
          description: "successful operation"
      x-swagger-router-controller: "swagger_server.controllers.product_controller"
definitions:
  User:
    type: "object"
    properties:
      userId:
        type: "string"
      authToken:
        type: "string"
    xml:
      name: "User"
    example:
      authToken: "authToken"
      userId: "userId"
  ProductInfo:
    type: "object"
    properties:
      topic:
        type: "string"
    xml:
      name: "ProductInfo"
    example:
      topic: "topic1"
  ProductQuery:
    type: "object"
    properties:
      userInfo:
        $ref: "#/definitions/User"
      productInfo:
        $ref: "#/definitions/ProductInfo"
    xml:
      name: "ProductQuery"
    example:
      userInfo:
        authToken: "authToken"
        userId: "userId"
      productInfo:
        topic: "topic1"
