# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TransactionInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, topic: str=None):  # noqa: E501
        """TransactionInfo - a model defined in Swagger

        :param topic: The topic of this TransactionInfo.  # noqa: E501
        :type topic: str
        """
        self.swagger_types = {
            'topic': str
        }

        self.attribute_map = {
            'topic': 'topic'
        }

        self._topic = topic

    @classmethod
    def from_dict(cls, dikt) -> 'TransactionInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TransactionInfo of this TransactionInfo.  # noqa: E501
        :rtype: TransactionInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def topic(self) -> str:
        """Gets the topic of this TransactionInfo.


        :return: The topic of this TransactionInfo.
        :rtype: str
        """
        return self._topic

    @topic.setter
    def topic(self, topic: str):
        """Sets the topic of this TransactionInfo.


        :param topic: The topic of this TransactionInfo.
        :type topic: str
        """

        self._topic = topic
